# -*- coding: utf-8 -*-
"""SE01 Data Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsxpBowVG8N67I8QbPRmDuYItzEBPak0
"""

# Define the data model
# Set up first the tasks
# In order to set up tasks, we need to differentiate between word tasks and text tasks
# So we first define words
print("==========Words============")
W001 = "kläder"
W002 = "en"
W003 = "t-shirt"
W004 = "t-shirtar"
W005 = "tröja"
W006 = "tröjor"
W007 = "skjorta"
W008 = "skjortor"
W009 = "blus"
W010 = "blusar"
W011 = "ett"
W012 = "linne"
W013 = "gul"
W014 = "gula"
W015 = "gult"
W016 = "röd"
W017 = "röda"
print(W001)
print(W002)
print(W003)
print(W004)
print(W005)
print(W006)
print(W007)
print(W008)
print(W009)
print(W010)
print(W011)
print(W012)
print(W013)
print(W014)
print(W015)
print(W016)
print(W017)
# With the words, we can now create word tasks as lists of words
print("==========Tasks============")
T001 = [W002, W013,W007]
print(T001)
T002 = [W017, W010]
print(T002)
T003 = [W011, W012]
print(T003)
# We can also set up text tasks
T004 = "en gul t-shirt"
print(T004)
T005 = "gula t-shirtar"
print(T005)
T006 = "ett gult linne"
print(T006)
# Now we can combine takss into exercises where we can combine both types of tasks
print("==========Exercises============")
E001 = [T001, T002, T006]
print(E001)
E002 = [T001, T005,T002]
print(E002)
E003 = [T001, T002,T003,T004]
print(E003)
# finally we can set up Lessons"
print("==========Lessons============")
L1 = [E001, E002, E003]
print(L1)
L2 = [E002, E001, E003]
print(L2)